# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true


    access_control: 
    #     - { path: ^/login$, role: IS_AUTHENTICETED_ANONYMOUSLY }
    #     - { path: ^/register, role: IS_AUTHENTICETED_ANONYMOUSLY }
    #     - { path: ^/logout, role: IS_AUTHENTICETED_ANONYMOUSLY }
    #    - { path: ^/resetting, role: IS_AUTHENTICETED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    encoders:
        FOS\UserBundle\Model\Userinterface: bcrypt
    role_hierarchy: 
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
